name: Machine Learning Pipeline

on:
  push:
    branches:
      - main
      - manu
  pull_request:
    branches:
      - main

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run multiclass model
      run: |
        python multiclass.py
      id: multiclass
      continue-on-error: true 

    - name: Run binary model
      run: |
        python binary.py
      id: binary
      continue-on-error: true

    - name: Run regression model
      run: |
        python regression.py
      id: regression
      continue-on-error: true
      
